/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MT4WebService_constants.h"



const MT4WebServiceConstants g_MT4WebService_constants;

MT4WebServiceConstants::MT4WebServiceConstants() {
}



