/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MT4WebService_CONSTANTS_H
#define MT4WebService_CONSTANTS_H

#include "MT4WebService_types.h"



class MT4WebServiceConstants {
 public:
  MT4WebServiceConstants();

};

extern const MT4WebServiceConstants g_MT4WebService_constants;



#endif
